// 获取所有用户信息
export const FETCH_ALL_USER_LIST = 'FETCH_ALL_USER_LIST';
export const FETCH_ALL_USER_LIST_SUCCESS = 'FETCH_ALL_USER_LIST_SUCCESS';
export const FETCH_ALL_USER_LIST_FAIL = 'FETCH_ALL_USER_LIST_FAIL';

// 用户注册
export const USER_REGISTER = 'USER_REGISTER';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';
export const RESET_REGISTER_STATUS = 'RESET_REGISTER_STATUS';

// 用户登录
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const RESET_LOGIN_STATUS = 'RESET_LOGIN_STATUS';
