// 获取所有用户信息
export const FETCH_ALL_USER_LIST = 'FETCH_ALL_USER_LIST';
export const FETCH_ALL_USER_LIST_SUCCESS = 'FETCH_ALL_USER_LIST_SUCCESS';
export const FETCH_ALL_USER_LIST_FAIL = 'FETCH_ALL_USER_LIST_FAIL';